apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ismailnijazi/inventory_management_productservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secrets
                  key: connection-string
          resources:
            requests:
              cpu: "400m"
              memory: "512Mi"
            limits:
              cpu: "600m"
              memory: "1024Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-clusterip
spec:
  selector:
    app: product-service
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product-service-hp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
